function(validate_cache_var var_name regex example)
  if(NOT "${${var_name}}" MATCHES "${regex}")
    message(FATAL_ERROR "${var_name}='${${var_name}}' does not match allowed pattern: ${regex} -- example: ${example}")
  endif()
endfunction()

function(add_opt_define target opt_name add_zero)
  if (${opt_name})
    target_compile_definitions(${target} PUBLIC ${opt_name}=1)
    message(STATUS "option: ${opt_name}: enabled")
  else()
    if (${add_zero})
      target_compile_definitions(${target} PUBLIC ${opt_name}=0)
    endif()
    message(STATUS "option: ${opt_name}: disabled")
  endif()
endfunction()

option(OPT_HID_SEND_QUAT "send quaternion data" OFF)
option(OPT_HID_SEND_INDICATORS "send debug indicators" OFF)
option(OPT_HID_SEND_DEBUG_COUNTERS "send debug counters" OFF)

option(OPT_OUTPUT_INVERT_YAW "Invert yaw output" ON)
option(OPT_OUTPUT_INVERT_PITCH "Invert pitch output" OFF)
option(OPT_OUTPUT_INVERT_ROLL "Invert roll output" OFF)

set(DEFAULT_CALIB__GYRO_HW "0, 0, 0" CACHE STRING "Default gyro hardware calibration offset")
set(DEFAULT_CALIB__GYRO_FINE "0.0, 0.0, 0.0" CACHE STRING "Default gyro fine calibration offset")
set(DEFAULT_CALIB__ACCEL_OFFSET "0.0, 0.0, 0.0" CACHE STRING "Default accel offset calibration")
set(DEFAULT_CALIB__ACCEL_MULTIPLIER "0.0" CACHE STRING "Default accel multiplier calibration")
set(DEFAULT_CALIB__MAG_GAIN "0.0, 0.0, 0.0" CACHE STRING "Default magnetometer gain calibration")
set(DEFAULT_CALIB__MAG_OFFS "0.0, 0.0, 0.0" CACHE STRING "Default magnetometer offset calibration")
set(DEFAULT_SLACK "0.3" CACHE STRING "Default slack (degrees)") 

set(RE_INTEGER " *-?[0-9]+ *")
set(RE_FLOAT " *-?[0-9]*\\.?[0-9]+(e-?[0-9]+)? *")
set(RE_INT3 "${RE_INTEGER},${RE_INTEGER},${RE_INTEGER}")
set(RE_VECTOR3 "${RE_FLOAT},${RE_FLOAT},${RE_FLOAT}")

validate_cache_var(DEFAULT_CALIB__GYRO_HW "${RE_INT3}" "139, 223, 85")
validate_cache_var(DEFAULT_CALIB__GYRO_FINE "${RE_VECTOR3}" "0.00026471857739211605, -0.00029203992232677015, -8.089260951242131e-05")
validate_cache_var(DEFAULT_CALIB__ACCEL_OFFSET "${RE_VECTOR3}" "-0.024252388693549568, -0.004464135930662227, -0.07690795675758028")
validate_cache_var(DEFAULT_CALIB__ACCEL_MULTIPLIER "${RE_FLOAT}" "6.067221999900171E-05")
validate_cache_var(DEFAULT_CALIB__MAG_GAIN "${RE_VECTOR3}" "0.000196539883413, 0.000186055059277, 0.000172237841480")
validate_cache_var(DEFAULT_CALIB__MAG_OFFS "${RE_VECTOR3}" "-0.130364540995749, 0.055779183952733, 1.072316097630281")
validate_cache_var(DEFAULT_SLACK "${RE_FLOAT}" "0.3")

message(STATUS "Default calibration values:")
message(STATUS "  GYRO_HW: ${DEFAULT_CALIB__GYRO_HW}")
message(STATUS "  GYRO_FINE: ${DEFAULT_CALIB__GYRO_FINE}")
message(STATUS "  ACCEL_OFFSET: ${DEFAULT_CALIB__ACCEL_OFFSET}")
message(STATUS "  ACCEL_MULTIPLIER: ${DEFAULT_CALIB__ACCEL_MULTIPLIER}")
message(STATUS "  MAG_GAIN: ${DEFAULT_CALIB__MAG_GAIN}")
message(STATUS "  MAG_OFFS: ${DEFAULT_CALIB__MAG_OFFS}")
message(STATUS "Default slack for rotation: ${DEFAULT_SLACK} degrees")