function(validate_cache_var var_name regex example)
  if(NOT "${${var_name}}" MATCHES "${regex}")
    message(FATAL_ERROR "${var_name}='${${var_name}}' does not match allowed pattern: ${regex} -- example: ${example}")
  endif()
endfunction()

function(add_opt_define target opt_name add_zero)
  if (${opt_name})
    target_compile_definitions(${target} PUBLIC ${opt_name}=1)
    message(STATUS "option: ${opt_name}: enabled")
  else()
    if (${add_zero})
      target_compile_definitions(${target} PUBLIC ${opt_name}=0)
    endif()
    message(STATUS "option: ${opt_name}: disabled")
  endif()
endfunction()

option(OPT_HID_SEND_QUAT "send quaternion data" OFF)
option(OPT_HID_SEND_INDICATORS "send debug indicators" OFF)
option(OPT_HID_SEND_DEBUG_COUNTERS "send debug counters" OFF)

option(OPT_OUTPUT_INVERT_YAW "Invert yaw output" ON)
option(OPT_OUTPUT_INVERT_PITCH "Invert pitch output" OFF)
option(OPT_OUTPUT_INVERT_ROLL "Invert roll output" OFF)

set(DEFAULT_DEVICE_ORIENTATION "TOP" CACHE STRING "Default device orientation")
set_property(CACHE DEFAULT_DEVICE_ORIENTATION PROPERTY STRINGS FRONT TOP)

set(DEFAULT_CALIB__GYRO_HW "0, 0, 0" CACHE STRING "Default gyro hardware calibration offset")
set(DEFAULT_CALIB__GYRO_FINE "0.0, 0.0, 0.0" CACHE STRING "Default gyro fine calibration offset")
set(DEFAULT_CALIB__ACCEL_BIAS "0.0, 0.0, 0.0" CACHE STRING "Default accel offset calibration")
set(DEFAULT_CALIB__ACCEL_ALIGN "1.0, 0.0, 1.0, 0.0, 0.0, 1.0" CACHE STRING "Default accel multiplier calibration")
set(DEFAULT_CALIB__MAG_GAIN "1.8E-4, 1.8E-4, 1.8E-4" CACHE STRING "Default magnetometer gain calibration")
set(DEFAULT_CALIB__MAG_OFFS "0.0, 0.0, 0.0" CACHE STRING "Default magnetometer offset calibration")
set(DEFAULT_SLACK "0.3" CACHE STRING "Default slack (degrees)") 

set(RE_INTEGER " *-?[0-9]+ *")
set(RE_FLOAT " *-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)? *")
set(RE_INT3 "${RE_INTEGER},${RE_INTEGER},${RE_INTEGER}")
set(RE_VECTOR3 "${RE_FLOAT},${RE_FLOAT},${RE_FLOAT}")
set(RE_VECTOR6 "${RE_FLOAT},${RE_FLOAT},${RE_FLOAT},${RE_FLOAT},${RE_FLOAT},${RE_FLOAT}")

validate_cache_var(DEFAULT_CALIB__GYRO_HW "${RE_INT3}" "139, 223, 85")
validate_cache_var(DEFAULT_CALIB__GYRO_FINE "${RE_VECTOR3}" "0.00026471857739211605, -0.00029203992232677015, -8.089260951242131e-05")
validate_cache_var(DEFAULT_CALIB__ACCEL_BIAS "${RE_VECTOR3}" "121.33169, -260.69307, 1094.31292")
validate_cache_var(DEFAULT_CALIB__ACCEL_ALIGN "${RE_VECTOR6}" "0.9968838, -0.0011559, 0.9974094, -0.0044594, 0.0013958, 0.9910061")
validate_cache_var(DEFAULT_CALIB__MAG_GAIN "${RE_VECTOR3}" "0.000196539883413, 0.000186055059277, 0.000172237841480")
validate_cache_var(DEFAULT_CALIB__MAG_OFFS "${RE_VECTOR3}" "-0.130364540995749, 0.055779183952733, 1.072316097630281")
validate_cache_var(DEFAULT_SLACK "${RE_FLOAT}" "0.3")

message(STATUS "Default device orientation: ${DEFAULT_DEVICE_ORIENTATION}")
message(STATUS "Default calibration values:")
message(STATUS "  GYRO_HW: ${DEFAULT_CALIB__GYRO_HW}")
message(STATUS "  GYRO_FINE: ${DEFAULT_CALIB__GYRO_FINE}")
message(STATUS "  ACCEL_BIAS: ${DEFAULT_CALIB__ACCEL_BIAS}")
message(STATUS "  ACCEL_ALIGN: ${DEFAULT_CALIB__ACCEL_ALIGN}")
message(STATUS "  MAG_GAIN: ${DEFAULT_CALIB__MAG_GAIN}")
message(STATUS "  MAG_OFFS: ${DEFAULT_CALIB__MAG_OFFS}")
message(STATUS "Default slack for rotation: ${DEFAULT_SLACK} degrees")
